apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  nodes_config.cfg: |
    {{- .Values.nodesConfig | nindent 4 }}
  config.cfg: |
    IMEX_CMD_PORT=50005
    IMEX_STATS_PORT=50006
    IMEX_LOG_FILE=/var/log/nvidia-imex.log
    IMEX_LOG_LEVEL=4
    IMEX_CONN_WAIT_TIMEOUT=15
    IMEX_ALLOW_INVALID_PEER_CERTS=1
