apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  nodes_config.cfg: |
    {{- .Values.nodesConfig | nindent 4 }}
  config.cfg: |
    IMEX_CMD_PORT=50005
    LOG_FILE_NAME=/var/log/nvidia-imex.log
    LOG_LEVEL=4
