apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ include "cluster.name" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.clusterLabels }}
  labels: {{- toYaml . | nindent 4}}
  {{- end }}
  {{- with .Values.clusterAnnotations }}
  annotations: {{- toYaml . | nindent 4}}
  {{- end }}
spec:
  {{- with .Values.clusterNetwork }}
  clusterNetwork:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  controlPlaneEndpoint:
    host: {{ .Values.k0s.api.externalAddress | default "127.0.0.1" }}
    port: {{ .Values.clusterNetwork.apiServerPort }}
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: K0sControlPlane
    name: {{ include "k0scontrolplane.name" . }}
    namespace: {{ .Release.Namespace }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: Metal3Cluster
    name: {{ include "cluster.name" . }}
    namespace: {{ .Release.Namespace }}
